# Generated by Django 3.0.7 on 2023-05-10 01:32

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imgBackground',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.upload_avatar_path_background),
        ),
    ]
