# Generated by Django 3.0.7 on 2023-05-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_imgbackground'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
