# Generated by Django 3.0.7 on 2023-05-22 03:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230517_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopost',
            name='repost',
            field=models.ManyToManyField(blank=True, related_name='repost', to=settings.AUTH_USER_MODEL),
        ),
    ]
