# Generated by Django 3.0.7 on 2023-05-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_monopost_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopost',
            name='reposting',
            field=models.BooleanField(default=False),
        ),
    ]
