# Generated by Django 3.0.7 on 2023-05-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_monopost_reposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopost',
            name='repostingFrom',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
