# Generated by Django 3.0.7 on 2023-05-22 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_monopost_repostingfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopost',
            name='repostingFromUser',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
