# Generated by Django 3.0.7 on 2023-05-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pageattribute_userintattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopage',
            name='attribute',
            field=models.ManyToManyField(blank=True, related_name='pageattributeid', to='api.PageAttribute'),
        ),
    ]
