# Generated by Django 3.0.7 on 2023-05-22 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_monopage_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pageId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followPageId', to='api.MonoPage')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
