# Generated by Django 3.0.7 on 2023-05-23 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_followingpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monopost',
            name='title',
        ),
    ]
