# Generated by Django 3.0.7 on 2023-05-24 10:35

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_monopost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(blank=True, null=True, upload_to=api.models.upload_affiliate_links_path)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
