# Generated by Django 3.0.7 on 2023-05-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_affiliatelinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopage',
            name='affiliateId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliateId', to='api.AffiliateLinks'),
        ),
    ]
