# Generated by Django 3.0.7 on 2023-05-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_monopage_affiliateid'),
    ]

    operations = [
        migrations.AddField(
            model_name='monopage',
            name='badpoint',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monopage',
            name='goodpoint',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
