# Generated by Django 3.2 on 2023-06-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20230622_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
