# Generated by Django 3.2 on 2023-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20230626_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='affiliatelinks',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
