# Generated by Django 3.2 on 2023-06-28 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20230628_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwningPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('pageId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OwningPageId', to='api.monopage')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwningUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
