# Generated by Django 4.1.7 on 2023-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_user_created_time_alter_user_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_key",
            field=models.EmailField(default="", max_length=100),
        ),
    ]
