# Generated by Django 4.1.7 on 2023-07-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_user_verification_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_key",
            field=models.IntegerField(null=True),
        ),
    ]
