# Generated by Django 4.1.7 on 2023-07-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_alter_user_verification_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(default="normal", max_length=50),
        ),
    ]
