# Generated by Django 4.2.5 on 2023-09-22 08:30

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='avatars/default.jpg', null=True, upload_to=api.models.upload_avatar_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='imgBackground',
            field=models.ImageField(blank=True, default='avatars/default_background.jpg', null=True, upload_to=api.models.upload_avatar_path_background),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickName',
            field=models.CharField(default='default', max_length=20),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
                ('url', models.CharField(max_length=50, null=True)),
                ('content', models.CharField(max_length=210)),
                ('img', models.ImageField(blank=True, upload_to=api.models.upload_advertisement_path)),
                ('target', models.IntegerField(default=0)),
                ('cnt', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stripe_flag', models.BooleanField(default=True)),
                ('del_flag', models.BooleanField(default=False)),
                ('allowed', models.BooleanField(default=False)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
